name: Update GitHub Statistics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub statistics
        uses: cicirello/user-statistician@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          image-file: profile/github-stats.svg
          include-title: true
          custom-title: "Moksh Jain's GitHub Statistics"
          colors: "0D1117 312E81 8B5CF6 A78BFA C4B5FD"
          border-radius: 6
          show-border: true
          max-languages: 8
          commit-and-push: true
